INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Alta Verapaz');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Baja Verapaz');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Chimaltenango');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Chiquimula');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('El Progreso');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Escuintla');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Guatemala');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Huehuetenango');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Izabal');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Jalapa');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Jutiapa');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Peten');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Quetzaltenango');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Quiche');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Retalhuleu');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Sacatepequez');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('San Marcos');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Santa Rosa');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Solola');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Suchitepequez');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Totonicapan');
INSERT INTO `water_laboratory`.`DEPARTMENT` (`name_department`) VALUES ('Zacapa');