INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Cobán', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Cruz Verapaz', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Cristóbal Verapaz', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Tactic', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Tamahú', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Tucurú', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Panzós', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Senahú', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Carchá', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Chamelco', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Lanquín', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa María Cahabón', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chisec', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chahal', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Fray Bartolomé de las Casas', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Catalina La Tinta', 1);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Raxruha', 1);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Salamá', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Cubulco', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Granados', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Purulhá', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Rabinal', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Jerónimo', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Miguel Chicaj', 2);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Cruz El Chol', 2);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chimaltenango', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Acatenango', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('El Tejar', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Parramos', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Patzicía', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Patzún', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Andrés Itzapa', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José Poaquil', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Comalapa', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Martín Jilotepeque', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Miguel Pochuta', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Yepocapa', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Apolonia', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Cruz Balanyá', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Tecpán Guatemala', 3);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Zaragoza', 3);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chiquimula', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Camotán', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Concepción Las Minas', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Esquipulas', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Ipala', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Jocotán', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Olopa', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Quezaltepeque', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Jacinto', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José La Arada', 4);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Ermita', 4);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Guastatoya', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('El Jícaro', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Morazán', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('S. Agustín Acasaguastlán', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Antonio La Paz', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Cristóbal Acasaguastlán', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Sanarate', 5);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Sansare', 5);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Escuintla', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Guanagazapa', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Iztapa', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('La Democracia', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('La Gomera', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Masagua', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Nueva Concepción', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Palín', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Vicente Pacaya', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Lucía Cotzumalguapa', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Sipacate', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Siquinalá', 6);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Tiquisate', 6);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Guatemala', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Catarina Pinula', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José Pinula', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José del Golfo', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Palencia', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chinautla', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Ayampuc', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Mixco', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Sacatepéquez', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Sacatepéquez', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Raymundo', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chuarrancho', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Fraijanes', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Amatitlán', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Villa Nueva', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Villa Canales', 7);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Petapa', 7);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Huehuetenango', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Aguacatán', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chiantla', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Colotenango', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Concepción Huista ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Cuilco', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Jacaltenango ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('La Democracia ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('La Libertad ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Malacatancito', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Nentón ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Antonio Huista ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Gaspar Ixchil ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Ildefonso Ixtahuacán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Atitán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Ixcoy ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Mateo Ixtatán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Miguel Acatán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Nécta ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Soloma ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Rafael La Independencia ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Rafael Pétzal ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Sebastián Coatán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Sebastián Huehuetenango ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Ana Huista ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Bárbara ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Cruz Barillas ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Eulalia ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santiago Chimaltenango ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Tectitán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Todos Santos Cuchumatán ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Unión Cantinil ', 8);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santiago Petatán ', 8);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Puerto Barrios', 9);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('El Estor', 9);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Livingston', 9);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Los Amates', 9);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Morales', 9);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Jalapa', 10);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Mataquescuintla', 10);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Monjas', 10);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Carlos Alzatate', 10);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Luis Jilotepeque', 10);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Manuel Chaparrón', 10);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pedro Pinula', 10);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Agua Blanca', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Asuncion Mita', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Atescatempa', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Comapa', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Conguaco', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Adelanto', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Progreso', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Jalpatagua', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Jerez', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Jutiapa', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Moyuta', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Pasaco', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Quesada', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Jose Acatempa', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Catarina Mita', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Yupiltepeque', 11);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Zapotitlan', 11);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Dolores', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Flores, Santa Elena de la Cruz', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('La Libertad', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Melchor de Mencos', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Poptun', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Andres', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Benito', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Francisco', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Jose', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Luis', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Ana', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Sayaxche', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Las Cruces', 12);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Chal', 12);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Almolonga', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Cabrican', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Cajola', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Cantel', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Coatepeque', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Colomba', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Concepcion Chiquirichapa', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Palmar', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Flores Costa Cuca', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Genova', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Huitan', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('La Esperanza', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Olintepeque', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Palestina de los Altos', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Quetzaltenango', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Salcaja', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Carlos Sija', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Juan Ostuncalco', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Francisco La Union', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Martin Sacatepequez', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Mateo', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Miguel Siguila', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Sibilia', 13);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Zunil', 13);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Cruz del Quiche', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Canilla', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Chajul', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Chicaman', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Chiche', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Chichicastenango', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Chinique', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Cunen', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Ixcan', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Joyabaj', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Pachalum', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Patzite', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Sacapulas', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Andres Sajcabaja', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Antonio Ilotenango', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Bartolome Jocotenango', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Juan Cotzal', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Pedro Jocopilas', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Maria Nebaj', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Uspantan', 14);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Zacualpa', 14);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Champerico', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Asintal', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Nuevo San Carlos', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Retalhuleu', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Andres Villa Seca', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Felipe', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Martin Zapotitlan', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Sebastian', 15);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Cruz Mulua', 15);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Alotenango', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('La Antigua Guatemala', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Ciudad Vieja', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Jocotenango', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Magdalena Milpas Altas', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Pastores', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Antonio Aguas Calientes', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Bartolome Milpas Altas', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Lucas Sacatepequez', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Miguel Dueñas', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Catarina Barahona', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Lucia Milpas Altas', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Maria de Jesus', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santiago Sacatepequez', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santo Domingo Xenacoj', 16);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Sumpango', 16);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Marcos', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Ayutla', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Catarina', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Camitancillo', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Concepción Tutuapa', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Quetzal', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Rodeo', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('El Tumbador', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Ixchiguan', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('La Reforma', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Malacatan', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Nuevo Progreso', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Ocos', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Pajapita', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Esquipulas Palo Gordo', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Antonio Sacatepequez', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Cristobal Cucho', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Jose Ojetenam', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Lorenzo', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Miguel Ixtahuacán', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Pablo', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Pedro Sacatepequez', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Rafael Pie de la Cuesta', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Sibinal', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Sipacapa', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Tacana', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Tajucumulco', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Tejutla', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Rio Blanco', 17);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('La Blanca', 17);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Barberena', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Casillas', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Chiquimulilla', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Cuilapa', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Guazacapan', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Monterrico', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Nueva Santa Rosa', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Oratorio', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Pueblo Nuevo Viñas', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Juan Tecuaco', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Rafael Las Flores', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Cruz Naranjo', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Maria Ixhuatan', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Rosa de Lima', 18);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Taxisco', 18);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Solola', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Concepcion', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Nahuala', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Panajachel', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Andres Semetabaj', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Antonio Palopo', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Jose Chacaya', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Juan La Laguna', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Lucas Toliman', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Marcos La Laguna', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Pablo La Laguna', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('San Pedro La Laguna', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Catarina Ixtahuacán', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Catarina Palopo', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Clara La Laguna', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Cruz La Laguna', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Lucia Utatlan', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santa Maria Visitacion', 19);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`,`department_id`) VALUES ('Santiago Atitlan', 19);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Mazatenango', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Chicacao', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Cuyotenango', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Patulul', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Pueblo Nuevo', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Río Bravo', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Samayac', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('S. Antonio Suchitepéquez', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Bernardino', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Francisco Zapotitlán', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Gabriel', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José El Ídolo', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San José La Maquina', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Juan Bautista', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Lorenzo', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Miguel Panán', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Pablo Jocopilas', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Bárbara', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('S. Domingo Suchitepéquez', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santo Tomás La Unión', 20);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Zunilito', 20);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Totonicapán', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Momostenango', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Andrés Xecul', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Bartolo Aguas Calientes', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Cristóbal Totonicapán', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Francisco El Alto', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa Lucía La Reforma', 21);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Santa María Chiquimula', 21);

INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Zacapa', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Cabañas', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Estanzuela', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Gualán', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Huité', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('La Unión', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Río Hondo', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Diego', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('San Jorge', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Teculután', 22);
INSERT INTO `water_laboratory`.`MUNICIPALITY` (`name_municipality`, `department_id`) VALUES ('Usumatlán', 22);